package models

// NormalizedEvent is the standard format that all normalizers produce.
type NormalizedEvent struct {
	Timestamp string `json:"timestamp"`
	Rule      struct {
		Level       int      `json:"level"`
		Description string   `json:"description"`
		ID          string   `json:"id"`
		Groups      []string `json:"groups"`
	} `json:"rule"`
	Agent struct {
		ID   string `json:"id"`
		Name string `json:"name"`
		IP   string `json:"ip"`
	} `json:"agent"`
	Manager struct {
		Name string `json:"name"`
	} `json:"manager"`
	Data struct {
		SrcIP   string `json:"srcip"`
		SrcPort string `json:"srcport"`
		DstUser string `json:"dstuser"`
	} `json:"data"`
	FullLog string `json:"full_log"`
	Decoder struct {
		Name string `json:"name"`
	} `json:"decoder"`
	Location string `json:"location"`
}

// CorrelationAlert defines the alert generated by the correlation engine.
type CorrelationAlert struct {
	Timestamp   int64  `json:"timestamp"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Severity    int    `json:"severity"` // 1-5 (5 is highest)
	SourceIP    string `json:"source_ip"`
}
