package models

import "time"

// NormalizedEvent is the standard format that all normalizers produce.
// This is the Wazuh-compatible format that all existing normalizers use.
type NormalizedEvent struct {
	Timestamp string `json:"timestamp"`
	Rule      struct {
		Level       int      `json:"level"`
		Description string   `json:"description"`
		ID          string   `json:"id"`
		Groups      []string `json:"groups"`
	} `json:"rule"`
	Agent struct {
		ID   string `json:"id"`
		Name string `json:"name"`
		IP   string `json:"ip"`
	} `json:"agent"`
	Manager struct {
		Name string `json:"name"`
	} `json:"manager"`
	Data struct {
		SrcIP   string `json:"srcip"`
		SrcPort string `json:"srcport"`
		DstUser string `json:"dstuser"`

		// ===== NEW FIELDS =====
		Username      string `json:"username"`       // Extracted username (e.g., "root", "admin")
		IsValidUser   bool   `json:"is_valid_user"`  // True if user exists in /etc/passwd
		ClientVersion string `json:"client_version"` // Client fingerprint (e.g., "OpenSSH_8.9p1")
		GeoCountry    string `json:"geo_country"`    // Default: "Local" for RFC1918
		// ============================================
	} `json:"data"`
	FullLog string `json:"full_log"`
	Decoder struct {
		Name string `json:"name"`
	} `json:"decoder"`
	Location string `json:"location"`
}

// NewNormalizedEvent returns a new event with all fields properly initialized.
// Existing normalizers can continue to set fields manually; new fields get safe defaults.
func NewNormalizedEvent() *NormalizedEvent {
	e := &NormalizedEvent{
		Timestamp: time.Now().UTC().Format("2006-01-02T15:04:05.000Z07:00"),
		FullLog:   "",
		Location:  "",
	}
	// Initialize Rule
	e.Rule.Level = 0
	e.Rule.Description = ""
	e.Rule.ID = ""
	e.Rule.Groups = []string{}

	// Initialize Agent
	e.Agent.ID = "000"
	e.Agent.Name = "unknown"
	e.Agent.IP = "127.0.0.1"

	// Initialize Manager
	e.Manager.Name = "SEIMlite"

	// Initialize Data (including new fields)
	e.Data.SrcIP = ""
	e.Data.SrcPort = ""
	e.Data.DstUser = ""
	e.Data.Username = ""
	e.Data.IsValidUser = false
	e.Data.ClientVersion = ""
	e.Data.GeoCountry = "Local" // Default for RFC1918/internal IPs

	// Initialize Decoder
	e.Decoder.Name = ""

	return e
}

// CorrelationAlert defines the alert generated by the correlation engine.
type CorrelationAlert struct {
	Timestamp   int64  `json:"timestamp"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Severity    int    `json:"severity"` // 1-5 (5 is highest)
	SourceIP    string `json:"source_ip"`

	// ===== NEW FIELDS =====
	RequiresAck bool   `json:"requires_ack"` // True for suspicious-but-not-confirmed logins
	RuleID      string `json:"rule_id"`      // Unique ID for the rule (for deduplication)
	// =====================

	EventIDs []int64 `json:"event_ids,omitempty"` // IDs of correlated events (future)
}

// NewCorrelationAlert creates an alert with default values.
func NewCorrelationAlert() *CorrelationAlert {
	return &CorrelationAlert{
		Timestamp:   time.Now().Unix(),
		Severity:    2,
		RequiresAck: false,
		RuleID:      "unknown",
		EventIDs:    []int64{},
	}
}
